# Pipeline Smoke Test

This notebook runs a deliberately tiny end-to-end pass through the forecasting and RL pipeline. 
It is meant to catch integration errors before starting the expensive full experiment.

In [1]:
%load_ext autoreload
%autoreload 2

## Imports And Paths

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "hybrid_pipeline").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT))
print(f"Project root: {PROJECT_ROOT}")

from hybrid_pipeline.core_pipeline import CONFIG, configure_vast_ai, prepare_data, print_task_summary
from hybrid_pipeline.experiment_runner import (
    run_experiment,
    build_cl_summary,
    build_fwt_details,
    build_forgetting_details,
    print_and_save_comparison_tables,
)
from hybrid_pipeline.trainers import LOGGER, compute_mase

Project root: C:\Users\Syakir\Downloads\Projects\fyp

C:\Users\Syakir\Downloads\Projects\fyp\.venv\Lib\site-packages\pytorch_forecasting\models\base\_base_model.py:30: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

## Runtime Setup

In [3]:
DATA_DIR = str(PROJECT_ROOT / "data" / "processed")
OUTPUT_DIR = str(PROJECT_ROOT / "outputs" / "hybrid_smoke_test")

configure_vast_ai(
    data_dir=DATA_DIR,
    output_dir=OUTPUT_DIR,
    require_gpu=False,  # set True on Vast.ai if you want to require CUDA
)

Runtime diagnostics

  Python         : 3.11.9

  PyTorch        : 2.3.1+cpu

  CUDA available : False

  CPU cores      : 12

  Vast.ai        : NO

  Active device  : CPU

  Precision      : 32

{'paths': {'demand_csv': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\data\\processed\\demand_forecasting.csv',
  'rl_csv': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\data\\processed\\rl_environment.csv',
  'checkpoints': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\outputs\\hybrid_smoke_test\\checkpoints',
  'results': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\outputs\\hybrid_smoke_test\\results',
  'logs': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\outputs\\hybrid_smoke_test\\logs',
  'plots': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\outputs\\hybrid_smoke_test\\plots'},
 'tasks': [{'task_id': 1,
   'name': 'Baseline_2023_H1',
   'start': '2023-01-01',
   'end': '2023-05-31',
   'regime': 'baseline'},
  {'task_id': 2,
   'name': 'MegaSale_2023',
   'start': '2023-06-01',
   'end': '2023-12-31',
   'regime': 'mega_sale'},
  {'task_id': 3,
   'name': 'Baseline_2024_H1',
   'start': '2024-01-01',
   'end': '2024-05-31',
   'regime': 'baseline'},
  {'task_id': 4,
   'name': 'MegaSale_2024',
   'start': '2024-06-01',
   'end': '2024-12-31',
   'regime': 'mega_sale'},
  {'task_id': 5,
   'name': 'Baseline_2025_H1',
   'start': '2025-01-01',
   'end': '2025-05-31',
   'regime': 'baseline'},
  {'task_id': 6,
   'name': 'MegaSale_2025',
   'start': '2025-06-01',
   'end': '2025-12-31',
   'regime': 'mega_sale'}],
 'model_types': ['forecasting', 'rl'],
 'cl_methods': {'forecasting': ['naive',
   'recall_ewc',
   'adaptive_drift',
   'drift_adaptive_replay_ewc'],
  'rl': ['naive',
   'recall_ewc',
   'adaptive_drift',
   'drift_adaptive_replay_ewc']},
 'forecasting': {'encoder_length': 60,
  'prediction_length': 14,
  'hidden_size': 128,
  'attention_head_size': 4,
  'dropout': 0.1,
  'hidden_continuous_size': 32,
  'output_size': 7,
  'learning_rate': 0.0003,
  'batch_size': 256,
  'max_epochs': 20,
  'early_stop_patience': 5,
  'gradient_clip': 0.1,
  'num_workers': 4,
  'group_ids': ['product_id', 'region_id'],
  'target': 'demand',
  'known_reals': ['time_idx',
   'day_of_week',
   'day_of_month',
   'week_of_year',
   'month',
   'quarter',
   'is_weekend',
   'is_federal_holiday',
   'is_ramadan',
   'ramadan_day',
   'is_pre_raya_window',
   'is_pre_cny_window',
   'is_mega_sale',
   'mega_sale_base_magnitude',
   'is_school_holiday',
   'is_government_payday_window',
   'is_private_payday_window',
   'social_media_index',
   'competitor_activity_index',
   'marketing_spend_myr'],
  'static_categoricals': ['product_id', 'region_id', 'product_category'],
  'static_reals': [],
  'time_varying_unknown_reals': ['demand']},
 'rl': {'learning_rate': 0.0003,
  'n_steps': 2048,
  'batch_size': 64,
  'n_epochs': 10,
  'gamma': 0.99,
  'gae_lambda': 0.95,
  'clip_range': 0.2,
  'ent_coef': 0.01,
  'vf_coef': 0.5,
  'max_grad_norm': 0.5,
  'total_timesteps_per_task': 50000,
  'eval_episodes': 10,
  'price_tiers': [-0.1,
   -0.08,
   -0.06,
   -0.04,
   -0.02,
   0.0,
   0.02,
   0.04,
   0.06,
   0.08,
   0.1],
  'n_actions': 11,
  'policy': 'MlpPolicy',
  'net_arch': [256, 256]},
 'cl': {'ewc_lambda': 400.0,
  'ewc_fisher_samples': 200,
  'replay_buffer_size': 2000,
  'replay_mix_ratio': 0.3,
  'recall_buffer_capacity': 20000,
  'recall_mix_n_steps': 512,
  'sdft_alpha': 0.5,
  'sdft_kl_coef': 0.1,
  'drift_ewc_min_scale': 0.25,
  'drift_ewc_max_scale': 1.25,
  'drift_distill_max_scale': 1.0,
  'drift_replay_min_scale': 0.5,
  'drift_replay_max_scale': 1.25},
 'hardware': {'device': 'cpu',
  'precision': '32',
  'compile': False,
  'compile_mode': 'reduce-overhead',
  'num_workers': 0,
  'pin_memory': False,
  'persistent_workers': False},
 'metrics': {'forecasting_primary': 'mase',
  'forecasting_secondary': ['smape', 'rmse'],
  'rl_primary': ['cumulative_profit', 'avg_episode_reward'],
  'rl_secondary': ['pricing_regret'],
  'cl_metrics': ['bwt', 'fwt', 'forgetting', 'avg_forgetting']}}

## Tiny Smoke-Test Configuration

In [4]:
# Keep this tiny. The goal is correctness, not final metrics.
CONFIG["tasks"] = CONFIG["tasks"][:2]
CONFIG["model_types"] = ["forecasting", "rl"]
CONFIG["cl_methods"] = {
    "forecasting": ["naive", "recall_ewc", "adaptive_drift", "drift_adaptive_replay_ewc"],
    "rl": ["naive", "recall_ewc", "adaptive_drift", "drift_adaptive_replay_ewc"],
}

CONFIG["forecasting"].update({
    "encoder_length": 28,
    "prediction_length": 7,
    "hidden_size": 16,
    "attention_head_size": 1,
    "hidden_continuous_size": 8,
    "batch_size": 64,
    "max_epochs": 1,
    "early_stop_patience": 1,
})

CONFIG["rl"].update({
    "total_timesteps_per_task": 256,
    "eval_episodes": 1,
    "n_steps": 128,
    "batch_size": 64,
    "n_epochs": 1,
    "net_arch": [32, 32],
})

CONFIG["cl"].update({
    "ewc_fisher_samples": 2,
    "replay_buffer_size": 128,
    "recall_buffer_capacity": 256,
    "recall_mix_n_steps": 32,
})

CONFIG["hardware"].update({
    "compile": False,
    "num_workers": 0,
    "persistent_workers": False,
})

print("Smoke-test config ready")
print("Tasks:", [t["name"] for t in CONFIG["tasks"]])
print("Forecast methods:", CONFIG["cl_methods"]["forecasting"])
print("RL methods:", CONFIG["cl_methods"]["rl"])

Smoke-test config ready
Tasks: ['Baseline_2023_H1', 'MegaSale_2023']
Forecast methods: ['naive', 'recall_ewc', 'adaptive_drift', 'drift_adaptive_replay_ewc']
RL methods: ['naive', 'recall_ewc', 'adaptive_drift', 'drift_adaptive_replay_ewc']

## Metric Sanity Check

In [5]:
mase_value = compute_mase([2, 3, 4], [2, 2, 5], list(range(20)), seasonality=7)
assert mase_value == mase_value and mase_value > 0, mase_value
print("MASE sanity check:", mase_value)

MASE sanity check: 0.09523809523809523

## Load Data

In [6]:
tft_tasks, rl_tasks, tft_df, rl_df = prepare_data()
print_task_summary(tft_tasks, rl_tasks)

assert len(tft_tasks) == len(CONFIG["tasks"])
assert len(rl_tasks) == len(CONFIG["tasks"])
assert all(len(df) > 0 for df in tft_tasks), "At least one TFT task is empty"
assert all(len(df) > 0 for df in rl_tasks), "At least one RL task is empty"
print("Data checks passed")

Loading datasets...

  Demand CSV  : 9,864 rows × 24 cols

  RL CSV      : 9,864 rows × 19 cols

✓ Data loaded and cleaned

┏━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┓
┃ Task ┃ Name             ┃ Period                   ┃ TFT rows ┃ RL rows ┃
┡━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━┩
│ 1    │ Baseline_2023_H1 │ 2023-01-01 -> 2023-05-31 │ 1,359    │ 1,359   │
│ 2    │ MegaSale_2023    │ 2023-06-01 -> 2023-12-31 │ 1,926    │ 1,926   │
└──────┴──────────────────┴──────────────────────────┴──────────┴─────────┘

Data checks passed

## Run Smoke Test

In [7]:
run_experiment(tft_tasks, rl_tasks)
print("Smoke-test training loop completed")

==============================================================

  CONTINUAL LEARNING EXPERIMENT START

==============================================================

═══ MODEL TYPE: FORECASTING ═══

  ── CL Method: naive ──

  Task 1/2: Baseline_2023_H1

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: mase=3.1013  smape=107.8053  rmse=1471.0547

  Evaluating on 1 future task(s) for FWT...

    Future eval task 2: mase=25.2427  smape=132.1915  rmse=1727.4077

  ★ New best naive MASE=3.1013

  Task 2/2: MegaSale_2023

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: mase=1.8394  smape=83.1787  rmse=1061.7655

    Eval task 2: mase=14.5819  smape=110.5400  rmse=990.5906

  ── CL Method: recall_ewc ──

  Task 1/2: Baseline_2023_H1

  Fisher computed over 2 batches

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: mase=1.1085  smape=120.1402  rmse=782.9374

  Evaluating on 1 future task(s) for FWT...

    Future eval task 2: mase=3.9161  smape=121.9101  rmse=286.5966

  ★ New best recall_ewc MASE=1.1085

  Task 2/2: MegaSale_2023

  Fisher computed over 2 batches

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: mase=1.1084  smape=118.5880  rmse=782.0838

    Eval task 2: mase=4.0290  smape=119.4468  rmse=295.4798

  ── CL Method: adaptive_drift ──

  Task 1/2: Baseline_2023_H1

  Fisher computed over 2 batches

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: mase=2.0337  smape=85.6333  rmse=1363.4697

  Evaluating on 1 future task(s) for FWT...

    Future eval task 2: mase=12.8700  smape=105.1398  rmse=900.6169

  ★ New best adaptive_drift MASE=2.0337

  Task 2/2: MegaSale_2023

  Forecast drift=0.405 ewc_scale=0.845 distill_scale=0.595

  Fisher computed over 2 batches

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: mase=2.0223  smape=85.0499  rmse=1361.3888

    Eval task 2: mase=12.2033  smape=102.8248  rmse=856.5063

  ── CL Method: drift_adaptive_replay_ewc ──

  Task 1/2: Baseline_2023_H1

  Fisher computed over 2 batches

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: mase=1.8550  smape=90.3793  rmse=1160.1268

  Evaluating on 1 future task(s) for FWT...

    Future eval task 2: mase=8.2766  smape=92.6105  rmse=572.7863

  ★ New best drift_adaptive_replay_ewc MASE=1.8550

  Task 2/2: MegaSale_2023

  Forecast drift=0.405 ewc_scale=0.845 replay_mix=0.284

  Fisher computed over 2 batches

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: mase=1.8870  smape=90.5195  rmse=1161.7690

    Eval task 2: mase=8.8096  smape=93.7928  rmse=607.5981

═══ MODEL TYPE: RL ═══

  ── CL Method: naive ──

  Task 1/2: Baseline_2023_H1

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: avg_episode_reward=5843.3176  cumulative_profit=42552591.9135  pricing_regret=31.9251

  Evaluating on 1 future task(s) for FWT...

    Future eval task 2: avg_episode_reward=7496.6994  cumulative_profit=45969978.4920  pricing_regret=21.9480

  Task 2/2: MegaSale_2023

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: avg_episode_reward=5807.3640  cumulative_profit=41852860.1194  pricing_regret=31.9516

    Eval task 2: avg_episode_reward=7380.6218  cumulative_profit=45797526.9238  pricing_regret=22.0083

  ── CL Method: recall_ewc ──

  Task 1/2: Baseline_2023_H1

  PPO Fisher computed over 10 steps

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: avg_episode_reward=5843.3176  cumulative_profit=42552591.9135  pricing_regret=31.9251

  Evaluating on 1 future task(s) for FWT...

    Future eval task 2: avg_episode_reward=7496.6994  cumulative_profit=45969978.4920  pricing_regret=21.9480

  Task 2/2: MegaSale_2023

  PPO Fisher computed over 10 steps

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: avg_episode_reward=5771.9321  cumulative_profit=44738179.3067  pricing_regret=31.9777

    Eval task 2: avg_episode_reward=7215.7543  cumulative_profit=41351209.8395  pricing_regret=22.0939

  ── CL Method: adaptive_drift ──

  Task 1/2: Baseline_2023_H1

  PPO Fisher computed over 10 steps

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: avg_episode_reward=5843.3176  cumulative_profit=42552591.9135  pricing_regret=31.9251

  Evaluating on 1 future task(s) for FWT...

    Future eval task 2: avg_episode_reward=7496.6994  cumulative_profit=45969978.4920  pricing_regret=21.9480

  Task 2/2: MegaSale_2023

  RL drift=0.336 ewc_scale=0.914 distill_scale=0.664

  PPO Fisher computed over 10 steps

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: avg_episode_reward=5949.9022  cumulative_profit=43020370.7880  pricing_regret=31.8468

    Eval task 2: avg_episode_reward=7800.6835  cumulative_profit=48384273.9161  pricing_regret=21.7908

  ── CL Method: drift_adaptive_replay_ewc ──

  Task 1/2: Baseline_2023_H1

  PPO Fisher computed over 10 steps

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: avg_episode_reward=5843.3176  cumulative_profit=42552591.9135  pricing_regret=31.9251

  Evaluating on 1 future task(s) for FWT...

    Future eval task 2: avg_episode_reward=7496.6994  cumulative_profit=45969978.4920  pricing_regret=21.9480

  Task 2/2: MegaSale_2023

  RL drift=0.336 ewc_scale=0.914 replay_mix_n=31 replay_coef=0.100

  PPO Fisher computed over 10 steps

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: avg_episode_reward=5843.0336  cumulative_profit=46902227.5936  pricing_regret=31.9254

    Eval task 2: avg_episode_reward=7408.4361  cumulative_profit=43728020.7899  pricing_regret=21.9939

  Results saved → C:\Users\Syakir\Downloads\Projects\fyp\outputs\hybrid_smoke_test\results\all_metrics.csv

═══ EXPERIMENT COMPLETE (2.9 min) ═══

Smoke-test training loop completed

## Validate Results

In [8]:
results_df = LOGGER.to_dataframe()
display(results_df.tail(20))

assert not results_df.empty, "No metrics were logged"
expected_model_types = set(CONFIG["model_types"])
assert expected_model_types.issubset(set(results_df["model_type"])), results_df["model_type"].unique()

forecast_df = results_df[results_df["model_type"] == "forecasting"]
rl_df_results = results_df[results_df["model_type"] == "rl"]
assert not forecast_df.empty, "No forecasting metrics logged"
assert not rl_df_results.empty, "No RL metrics logged"

# MASE can be NaN if a deliberately tiny smoke split has insufficient scale,
# but sMAPE/RMSE and RL metrics should exist.
assert {"smape", "rmse"}.issubset(set(forecast_df["metric_name"])), forecast_df["metric_name"].unique()
assert "cumulative_profit" in set(rl_df_results["metric_name"]), rl_df_results["metric_name"].unique()

print("Logged metrics:")
print(results_df.groupby(["model_type", "cl_method", "metric_name"]).size())
print("Smoke test passed")

,model_type,cl_method,train_task_id,eval_task_id,eval_phase,metric_name,metric_value,timestamp
92,rl,drift_adaptive_replay_ewc,2,1,seen,pricing_regret,3.192541e+01,2026-06-03T22:02:29
93,rl,drift_adaptive_replay_ewc,2,2,seen,avg_episode_reward,7.408436e+03,2026-06-03T22:02:29
94,rl,drift_adaptive_replay_ewc,2,2,seen,cumulative_profit,4.372802e+07,2026-06-03T22:02:29
95,rl,drift_adaptive_replay_ewc,2,2,seen,pricing_regret,2.199385e+01,2026-06-03T22:02:29
96,rl,naive,1,1,seen,profit_index,1.000000e+00,2026-06-03T22:02:30
97,rl,naive,1,2,future,profit_index,1.003766e+00,2026-06-03T22:02:30
98,rl,naive,2,1,seen,profit_index,9.835561e-01,2026-06-03T22:02:30
99,rl,naive,2,2,seen,profit_index,1.000000e+00,2026-06-03T22:02:30
100,rl,recall_ewc,1,1,seen,profit_index,1.000000e+00,2026-06-03T22:02:30
101,rl,recall_ewc,1,2,future,profit_index,1.003766e+00,2026-06-03T22:02:30
102,rl,recall_ewc,2,1,seen,profit_index,1.051362e+00,2026-06-03T22:02:30
103,rl,recall_ewc,2,2,seen,profit_index,9.029136e-01,2026-06-03T22:02:30
104,rl,adaptive_drift,1,1,seen,profit_index,1.000000e+00,2026-06-03T22:02:30
105,rl,adaptive_drift,1,2,future,profit_index,1.003766e+00,2026-06-03T22:02:30
106,rl,adaptive_drift,2,1,seen,profit_index,1.010993e+00,2026-06-03T22:02:30
107,rl,adaptive_drift,2,2,seen,profit_index,1.056482e+00,2026-06-03T22:02:30
108,rl,drift_adaptive_replay_ewc,1,1,seen,profit_index,1.000000e+00,2026-06-03T22:02:30
109,rl,drift_adaptive_replay_ewc,1,2,future,profit_index,1.003766e+00,2026-06-03T22:02:30
110,rl,drift_adaptive_replay_ewc,2,1,seen,profit_index,1.102218e+00,2026-06-03T22:02:30
111,rl,drift_adaptive_replay_ewc,2,2,seen,profit_index,9.548118e-01,2026-06-03T22:02:30

Logged metrics:
model_type   cl_method                  metric_name
forecasting  adaptive_drift             mase                  4
                                        rmse                  4
                                        smape                 4
             drift_adaptive_replay_ewc  mase                  4
                                        rmse                  4
                                        smape                 4
             naive                      mase                  4
                                        rmse                  4
                                        smape                 4
             recall_ewc                 mase                  4
                                        rmse                  4
                                        smape                 4
rl           adaptive_drift             avg_episode_reward    4
                                        cumulative_profit     4
                                        pricing_regret        4
                                        profit_index          4
             drift_adaptive_replay_ewc  avg_episode_reward    4
                                        cumulative_profit     4
                                        pricing_regret        4
                                        profit_index          4
             naive                      avg_episode_reward    4
                                        cumulative_profit     4
                                        pricing_regret        4
                                        profit_index          4
             recall_ewc                 avg_episode_reward    4
                                        cumulative_profit     4
                                        pricing_regret        4
                                        profit_index          4
dtype: int64
Smoke test passed

## Optional Summary Tables

In [9]:
cl_summary = build_cl_summary()
fwt_details = build_fwt_details(save=False)
forgetting_details = build_forgetting_details(save=False)
tables = print_and_save_comparison_tables(cl_summary)
cl_summary

  FWT details saved -> C:\Users\Syakir\Downloads\Projects\fyp\outputs\hybrid_smoke_test\results\fwt_details.csv

  Forgetting details saved ->
C:\Users\Syakir\Downloads\Projects\fyp\outputs\hybrid_smoke_test\results\forgetting_details.csv

CL Summary (BWT / FWT / Forgetting):

 model_type                 cl_method primary_metric  avg_final_perf  avg_online_perf     bwt     fwt  forgetting
avg_forgetting
forecasting                     naive           mase          8.2106           8.8416  1.2620  0.0000      0.0000
0.0000
forecasting                recall_ewc           mase          2.5687           2.5688  0.0001 21.3267      0.0000
0.0000
forecasting            adaptive_drift           mase          7.1128           7.1185  0.0113 12.3727      0.0000
0.0000
forecasting drift_adaptive_replay_ewc           mase          5.3483           5.3323 -0.0320 16.9661      0.0320
0.0320
         rl                     naive   profit_index          0.9918           1.0000 -0.0164  0.0000      0.0164
0.0164
         rl                recall_ewc   profit_index          0.9771           0.9515  0.0514  0.0000      0.0000
0.0000
         rl            adaptive_drift   profit_index          1.0337           1.0282  0.0110  0.0000      0.0000
0.0000
         rl drift_adaptive_replay_ewc   profit_index          1.0285           0.9774  0.1022  0.0000      0.0000
0.0000

==============================================================
  FORECASTING - MASE (lower is better)
==============================================================
                           Task 1   Task 2
cl_method
adaptive_drift             2.0337  12.2033
drift_adaptive_replay_ewc  1.8550   8.8096
naive                      3.1013  14.5819
recall_ewc                 1.1085   4.0290

==============================================================
  FORECASTING - sMAPE
==============================================================
                             Task 1    Task 2
cl_method
adaptive_drift              85.6333  102.8248
drift_adaptive_replay_ewc   90.3793   93.7928
naive                      107.8053  110.5400
recall_ewc                 120.1402  119.4468

==============================================================
  RL - PROFIT INDEX (vs naive fresh per-task, higher is better)
==============================================================
                           Task 1  Task 2
cl_method
adaptive_drift                1.0  1.0565
drift_adaptive_replay_ewc     1.0  0.9548
naive                         1.0  1.0000
recall_ewc                    1.0  0.9029

==============================================================
  RL - CUMULATIVE PROFIT (raw MYR, reference)
==============================================================
                                 Task 1        Task 2
cl_method
adaptive_drift             4.255259e+07  4.838427e+07
drift_adaptive_replay_ewc  4.255259e+07  4.372802e+07
naive                      4.255259e+07  4.579753e+07
recall_ewc                 4.255259e+07  4.135121e+07

==============================================================
  RL - PRICING REGRET (lower is better)
==============================================================
                            Task 1   Task 2
cl_method
adaptive_drift             31.9251  21.7908
drift_adaptive_replay_ewc  31.9251  21.9939
naive                      31.9251  22.0083
recall_ewc                 31.9251  22.0939

==============================================================
  CL METRICS - BWT / FWT / FORGETTING SUMMARY
==============================================================
 model_type                 cl_method primary_metric  avg_final_perf  avg_online_perf     bwt     fwt  forgetting  avg_forgetting
forecasting                     naive           mase          8.2106           8.8416  1.2620  0.0000      0.0000          0.0000
forecasting                recall_ewc           mase          2.5687           2.5688  0.0001 21.3267      0.0000          0.0000
forecasting            adaptive_drift           mase          7.1128           7.1185  0.0113 12.3727      0.0000          0.0000
forecasting drift_adaptive_replay_ewc           mase          5.3483           5.3323 -0.0320 16.9661      0.0320          0.0320
         rl                     naive   profit_index          0.9918           1.0000 -0.0164  0.0000      0.0164          0.0164
         rl                recall_ewc   profit_index          0.9771           0.9515  0.0514  0.0000      0.0000          0.0000
         rl            adaptive_drift   profit_index          1.0337           1.0282  0.0110  0.0000      0.0000          0.0000
         rl drift_adaptive_replay_ewc   profit_index          1.0285           0.9774  0.1022  0.0000      0.0000          0.0000

,model_type,cl_method,primary_metric,avg_final_perf,avg_online_perf,bwt,fwt,forgetting,avg_forgetting
0,forecasting,naive,mase,8.2106,8.8416,1.2620,0.0000,0.0000,0.0000
1,forecasting,recall_ewc,mase,2.5687,2.5688,0.0001,21.3267,0.0000,0.0000
2,forecasting,adaptive_drift,mase,7.1128,7.1185,0.0113,12.3727,0.0000,0.0000
3,forecasting,drift_adaptive_replay_ewc,mase,5.3483,5.3323,-0.0320,16.9661,0.0320,0.0320
4,rl,naive,profit_index,0.9918,1.0000,-0.0164,0.0000,0.0164,0.0164
5,rl,recall_ewc,profit_index,0.9771,0.9515,0.0514,0.0000,0.0000,0.0000
6,rl,adaptive_drift,profit_index,1.0337,1.0282,0.0110,0.0000,0.0000,0.0000
7,rl,drift_adaptive_replay_ewc,profit_index,1.0285,0.9774,0.1022,0.0000,0.0000,0.0000