# Pipeline Smoke Test

This notebook runs a deliberately tiny end-to-end pass through the forecasting and RL pipeline. 
It is meant to catch integration errors before starting the expensive full experiment.

In [1]:
%load_ext autoreload
%autoreload 2

## Imports And Paths

In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "fyp_pipeline").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT))
print(f"Project root: {PROJECT_ROOT}")

from fyp_pipeline.core_pipeline import CONFIG, configure_vast_ai, prepare_data, print_task_summary
from fyp_pipeline.experiment_runner import (
    run_experiment,
    build_cl_summary,
    print_and_save_comparison_tables,
)
from fyp_pipeline.trainers import LOGGER, compute_mase

Project root: c:\Users\Syakir\Downloads\Projects\fyp

c:\Users\Syakir\Downloads\Projects\fyp\.venv\Lib\site-packages\pytorch_forecasting\models\base\_base_model.py:30: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

## Runtime Setup

In [3]:
DATA_DIR = str(PROJECT_ROOT / "data" / "processed")
OUTPUT_DIR = str(PROJECT_ROOT / "outputs" / "smoke_test")

configure_vast_ai(
    data_dir=DATA_DIR,
    output_dir=OUTPUT_DIR,
    require_gpu=False,  # set True on Vast.ai if you want to require CUDA
)

Runtime diagnostics

  Python         : 3.11.9

  PyTorch        : 2.3.1+cpu

  CUDA available : False

  CPU cores      : 12

  Vast.ai        : NO

  Active device  : CPU

  Precision      : 32

{'paths': {'demand_csv': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\data\\processed\\demand_forecasting.csv',
  'rl_csv': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\data\\processed\\rl_environment.csv',
  'checkpoints': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\outputs\\smoke_test\\checkpoints',
  'results': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\outputs\\smoke_test\\results',
  'logs': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\outputs\\smoke_test\\logs',
  'plots': 'C:\\Users\\Syakir\\Downloads\\Projects\\fyp\\outputs\\smoke_test\\plots'},
 'tasks': [{'task_id': 1,
   'name': 'Baseline_2023_H1',
   'start': '2023-01-01',
   'end': '2023-05-31',
   'regime': 'baseline'},
  {'task_id': 2,
   'name': 'MegaSale_2023',
   'start': '2023-06-01',
   'end': '2023-12-31',
   'regime': 'mega_sale'},
  {'task_id': 3,
   'name': 'Baseline_2024_H1',
   'start': '2024-01-01',
   'end': '2024-05-31',
   'regime': 'baseline'},
  {'task_id': 4,
   'name': 'MegaSale_2024',
   'start': '2024-06-01',
   'end': '2024-12-31',
   'regime': 'mega_sale'},
  {'task_id': 5,
   'name': 'Baseline_2025_H1',
   'start': '2025-01-01',
   'end': '2025-05-31',
   'regime': 'baseline'},
  {'task_id': 6,
   'name': 'MegaSale_2025',
   'start': '2025-06-01',
   'end': '2025-12-31',
   'regime': 'mega_sale'}],
 'model_types': ['forecasting', 'rl'],
 'cl_methods': {'forecasting': ['naive', 'ewc', 'replay', 'sdft'],
  'rl': ['naive', 'ewc', 'recall', 'sdft']},
 'forecasting': {'encoder_length': 60,
  'prediction_length': 14,
  'hidden_size': 128,
  'attention_head_size': 4,
  'dropout': 0.1,
  'hidden_continuous_size': 32,
  'output_size': 7,
  'learning_rate': 0.0003,
  'batch_size': 256,
  'max_epochs': 20,
  'early_stop_patience': 5,
  'gradient_clip': 0.1,
  'num_workers': 4,
  'group_ids': ['product_id', 'region_id'],
  'target': 'demand',
  'known_reals': ['time_idx',
   'day_of_week',
   'day_of_month',
   'week_of_year',
   'month',
   'quarter',
   'is_weekend',
   'is_federal_holiday',
   'is_ramadan',
   'ramadan_day',
   'is_pre_raya_window',
   'is_pre_cny_window',
   'is_mega_sale',
   'mega_sale_base_magnitude',
   'is_school_holiday',
   'is_government_payday_window',
   'is_private_payday_window',
   'social_media_index',
   'competitor_activity_index',
   'marketing_spend_myr'],
  'static_categoricals': ['product_id', 'region_id', 'product_category'],
  'static_reals': [],
  'time_varying_unknown_reals': ['demand']},
 'rl': {'learning_rate': 0.0003,
  'n_steps': 2048,
  'batch_size': 64,
  'n_epochs': 10,
  'gamma': 0.99,
  'gae_lambda': 0.95,
  'clip_range': 0.2,
  'ent_coef': 0.01,
  'vf_coef': 0.5,
  'max_grad_norm': 0.5,
  'total_timesteps_per_task': 50000,
  'eval_episodes': 10,
  'price_tiers': [-0.1, -0.05, 0.0, 0.05, 0.1],
  'n_actions': 5,
  'policy': 'MlpPolicy',
  'net_arch': [256, 256]},
 'cl': {'ewc_lambda': 400.0,
  'ewc_fisher_samples': 200,
  'replay_buffer_size': 2000,
  'replay_mix_ratio': 0.3,
  'recall_buffer_capacity': 20000,
  'recall_mix_n_steps': 512,
  'sdft_alpha': 0.5,
  'sdft_temperature': 2.0,
  'sdft_kl_coef': 0.1},
 'hardware': {'device': 'cpu',
  'precision': '32',
  'compile': False,
  'compile_mode': 'reduce-overhead',
  'num_workers': 0,
  'pin_memory': False,
  'persistent_workers': False},
 'metrics': {'forecasting_primary': 'mase',
  'forecasting_secondary': ['smape', 'rmse'],
  'rl_primary': ['cumulative_profit', 'avg_episode_reward'],
  'rl_secondary': ['pricing_regret'],
  'cl_metrics': ['bwt', 'fwt']}}

## Tiny Smoke-Test Configuration

In [4]:
# Keep this tiny. The goal is correctness, not final metrics.
CONFIG["tasks"] = CONFIG["tasks"][:2]
CONFIG["model_types"] = ["forecasting", "rl"]
CONFIG["cl_methods"] = {
    "forecasting": ["naive", "ewc", "replay", "sdft"],
    "rl": ["naive", "ewc", "recall", "sdft"],
}

CONFIG["forecasting"].update({
    "encoder_length": 28,
    "prediction_length": 7,
    "hidden_size": 16,
    "attention_head_size": 1,
    "hidden_continuous_size": 8,
    "batch_size": 64,
    "max_epochs": 1,
    "early_stop_patience": 1,
})

CONFIG["rl"].update({
    "total_timesteps_per_task": 256,
    "eval_episodes": 1,
    "n_steps": 128,
    "batch_size": 64,
    "n_epochs": 1,
    "net_arch": [32, 32],
})

CONFIG["cl"].update({
    "ewc_fisher_samples": 2,
    "replay_buffer_size": 128,
    "recall_buffer_capacity": 256,
    "recall_mix_n_steps": 32,
})

CONFIG["hardware"].update({
    "compile": False,
    "num_workers": 0,
    "persistent_workers": False,
})

print("Smoke-test config ready")
print("Tasks:", [t["name"] for t in CONFIG["tasks"]])
print("Forecast methods:", CONFIG["cl_methods"]["forecasting"])
print("RL methods:", CONFIG["cl_methods"]["rl"])

Smoke-test config ready
Tasks: ['Baseline_2023_H1', 'MegaSale_2023']
Forecast methods: ['naive', 'ewc', 'replay', 'sdft']
RL methods: ['naive', 'ewc', 'recall', 'sdft']

## Metric Sanity Check

In [5]:
mase_value = compute_mase([2, 3, 4], [2, 2, 5], list(range(20)), seasonality=7)
assert mase_value == mase_value and mase_value > 0, mase_value
print("MASE sanity check:", mase_value)

MASE sanity check: 0.09523809523809523

## Load Data

In [6]:
tft_tasks, rl_tasks, tft_df, rl_df = prepare_data()
print_task_summary(tft_tasks, rl_tasks)

assert len(tft_tasks) == len(CONFIG["tasks"])
assert len(rl_tasks) == len(CONFIG["tasks"])
assert all(len(df) > 0 for df in tft_tasks), "At least one TFT task is empty"
assert all(len(df) > 0 for df in rl_tasks), "At least one RL task is empty"
print("Data checks passed")

Loading datasets...

  Demand CSV  : 9,864 rows × 66 cols

  RL CSV      : 9,864 rows × 86 cols

✓ Data loaded and cleaned

┏━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┓
┃ Task ┃ Name             ┃ Period                   ┃ TFT rows ┃ RL rows ┃
┡━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━┩
│ 1    │ Baseline_2023_H1 │ 2023-01-01 -> 2023-05-31 │ 1,359    │ 1,359   │
│ 2    │ MegaSale_2023    │ 2023-06-01 -> 2023-12-31 │ 1,926    │ 1,926   │
└──────┴──────────────────┴──────────────────────────┴──────────┴─────────┘

Data checks passed

## Run Smoke Test

In [7]:
run_experiment(tft_tasks, rl_tasks)
print("Smoke-test training loop completed")

==============================================================

  CONTINUAL LEARNING EXPERIMENT START

==============================================================

═══ MODEL TYPE: FORECASTING ═══

  ── CL Method: naive ──

  Task 1/2: Baseline_2023_H1

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: mase=3.1013  smape=107.8053  rmse=1471.0547

  ★ New best naive MASE=3.1013

  Task 2/2: MegaSale_2023

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: mase=1.8342  smape=83.1707  rmse=1062.2178

    Eval task 2: mase=2.2640  smape=111.2807  rmse=1000.5150

  ★ New best naive MASE=2.0491

  ── CL Method: ewc ──

  Task 1/2: Baseline_2023_H1

  Fisher computed over 2 batches

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: mase=2.9193  smape=104.7100  rmse=1412.8750

  ★ New best ewc MASE=2.9193

  Task 2/2: MegaSale_2023

  Fisher computed over 2 batches

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: mase=2.8932  smape=104.2766  rmse=1402.8478

    Eval task 2: mase=3.6191  smape=131.6897  rmse=1592.2323

  ── CL Method: replay ──

  Task 1/2: Baseline_2023_H1

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: mase=2.4711  smape=100.3885  rmse=1214.8386

  ★ New best replay MASE=2.4711

  Task 2/2: MegaSale_2023

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: mase=1.7295  smape=81.7497  rmse=1036.2216

    Eval task 2: mase=1.9556  smape=104.0968  rmse=876.1229

  ★ New best replay MASE=1.8425

  ── CL Method: sdft ──

  Task 1/2: Baseline_2023_H1

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: mase=1.5600  smape=100.6946  rmse=1047.4094

  ★ New best sdft MASE=1.5600

  Task 2/2: MegaSale_2023

  SDFT teacher updated from task 1

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: mase=1.5589  smape=99.5883  rmse=1082.1604

    Eval task 2: mase=0.4903  smape=122.6640  rmse=235.1597

  ★ New best sdft MASE=1.0246

═══ MODEL TYPE: RL ═══

  ── CL Method: naive ──

  Task 1/2: Baseline_2023_H1

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: avg_episode_reward=6017.2150  cumulative_profit=43201468.7749  pricing_regret=31.7976

  Task 2/2: MegaSale_2023

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: avg_episode_reward=5995.4364  cumulative_profit=43383685.6254  pricing_regret=31.8136

    Eval task 2: avg_episode_reward=7681.3743  cumulative_profit=45112342.8456  pricing_regret=21.8526

  ── CL Method: ewc ──

  Task 1/2: Baseline_2023_H1

  PPO Fisher computed over 10 steps

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: avg_episode_reward=6017.2150  cumulative_profit=43201468.7749  pricing_regret=31.7976

  Task 2/2: MegaSale_2023

  PPO Fisher computed over 10 steps

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: avg_episode_reward=5951.5927  cumulative_profit=43012552.8731  pricing_regret=31.8458

    Eval task 2: avg_episode_reward=7691.3503  cumulative_profit=44484756.8895  pricing_regret=21.8476

  ── CL Method: recall ──

  Task 1/2: Baseline_2023_H1

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: avg_episode_reward=6017.2150  cumulative_profit=43201468.7749  pricing_regret=31.7976

  Task 2/2: MegaSale_2023

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: avg_episode_reward=5864.4449  cumulative_profit=42241364.4640  pricing_regret=31.9096

    Eval task 2: avg_episode_reward=7464.9740  cumulative_profit=43322246.9298  pricing_regret=21.9645

  ── CL Method: sdft ──

  Task 1/2: Baseline_2023_H1

  ✓ Training complete

  Evaluating on 1 seen task(s)...

    Eval task 1: avg_episode_reward=6017.2150  cumulative_profit=43201468.7749  pricing_regret=31.7976

  Task 2/2: MegaSale_2023

  SDFT teacher updated from task 1

  ✓ Training complete

  Evaluating on 2 seen task(s)...

    Eval task 1: avg_episode_reward=5994.6390  cumulative_profit=43381647.5254  pricing_regret=31.8141

    Eval task 2: avg_episode_reward=7701.6213  cumulative_profit=45146278.6459  pricing_regret=21.8422

  Results saved → C:\Users\Syakir\Downloads\Projects\fyp\outputs\smoke_test\results\all_metrics.csv

═══ EXPERIMENT COMPLETE (2.2 min) ═══

Smoke-test training loop completed

## Validate Results

In [8]:
results_df = LOGGER.to_dataframe()
display(results_df.tail(20))

assert not results_df.empty, "No metrics were logged"
expected_model_types = set(CONFIG["model_types"])
assert expected_model_types.issubset(set(results_df["model_type"])), results_df["model_type"].unique()

forecast_df = results_df[results_df["model_type"] == "forecasting"]
rl_df_results = results_df[results_df["model_type"] == "rl"]
assert not forecast_df.empty, "No forecasting metrics logged"
assert not rl_df_results.empty, "No RL metrics logged"

# MASE can be NaN if a deliberately tiny smoke split has insufficient scale,
# but sMAPE/RMSE and RL metrics should exist.
assert {"smape", "rmse"}.issubset(set(forecast_df["metric_name"])), forecast_df["metric_name"].unique()
assert "cumulative_profit" in set(rl_df_results["metric_name"]), rl_df_results["metric_name"].unique()

print("Logged metrics:")
print(results_df.groupby(["model_type", "cl_method", "metric_name"]).size())
print("Smoke test passed")

,model_type,cl_method,train_task_id,eval_task_id,metric_name,metric_value,timestamp
52,rl,ewc,2,2,cumulative_profit,4.448476e+07,2026-05-06T22:31:52
53,rl,ewc,2,2,pricing_regret,2.184758e+01,2026-05-06T22:31:52
54,rl,recall,1,1,avg_episode_reward,6.017215e+03,2026-05-06T22:31:53
55,rl,recall,1,1,cumulative_profit,4.320147e+07,2026-05-06T22:31:53
56,rl,recall,1,1,pricing_regret,3.179759e+01,2026-05-06T22:31:53
57,rl,recall,2,1,avg_episode_reward,5.864445e+03,2026-05-06T22:31:54
58,rl,recall,2,1,cumulative_profit,4.224136e+07,2026-05-06T22:31:54
59,rl,recall,2,1,pricing_regret,3.190956e+01,2026-05-06T22:31:54
60,rl,recall,2,2,avg_episode_reward,7.464974e+03,2026-05-06T22:31:55
61,rl,recall,2,2,cumulative_profit,4.332225e+07,2026-05-06T22:31:55
62,rl,recall,2,2,pricing_regret,2.196449e+01,2026-05-06T22:31:55
63,rl,sdft,1,1,avg_episode_reward,6.017215e+03,2026-05-06T22:31:56
64,rl,sdft,1,1,cumulative_profit,4.320147e+07,2026-05-06T22:31:56
65,rl,sdft,1,1,pricing_regret,3.179759e+01,2026-05-06T22:31:56
66,rl,sdft,2,1,avg_episode_reward,5.994639e+03,2026-05-06T22:31:57
67,rl,sdft,2,1,cumulative_profit,4.338165e+07,2026-05-06T22:31:57
68,rl,sdft,2,1,pricing_regret,3.181415e+01,2026-05-06T22:31:57
69,rl,sdft,2,2,avg_episode_reward,7.701621e+03,2026-05-06T22:31:57
70,rl,sdft,2,2,cumulative_profit,4.514628e+07,2026-05-06T22:31:57
71,rl,sdft,2,2,pricing_regret,2.184219e+01,2026-05-06T22:31:57

Logged metrics:
model_type   cl_method  metric_name
forecasting  ewc        mase                  3
                        rmse                  3
                        smape                 3
             naive      mase                  3
                        rmse                  3
                        smape                 3
             replay     mase                  3
                        rmse                  3
                        smape                 3
             sdft       mase                  3
                        rmse                  3
                        smape                 3
rl           ewc        avg_episode_reward    3
                        cumulative_profit     3
                        pricing_regret        3
             naive      avg_episode_reward    3
                        cumulative_profit     3
                        pricing_regret        3
             recall     avg_episode_reward    3
                        cumulative_profit     3
                        pricing_regret        3
             sdft       avg_episode_reward    3
                        cumulative_profit     3
                        pricing_regret        3
dtype: int64
Smoke test passed

## Optional Summary Tables

In [9]:
cl_summary = build_cl_summary()
tables = print_and_save_comparison_tables(cl_summary)
cl_summary

CL Summary (BWT / FWT):

 model_type cl_method    primary_metric  avg_final_perf  avg_online_perf  bwt  fwt
forecasting     naive              mase    2.049100e+00     2.682600e+00  0.0  0.0
forecasting       ewc              mase    3.256200e+00     3.269200e+00  0.0  0.0
forecasting    replay              mase    1.842500e+00     2.213400e+00  0.0  0.0
forecasting      sdft              mase    1.024600e+00     1.025200e+00  0.0  0.0
         rl     naive cumulative_profit    4.424801e+07     4.415691e+07  0.0  0.0
         rl       ewc cumulative_profit    4.374865e+07     4.384311e+07  0.0  0.0
         rl    recall cumulative_profit    4.278181e+07     4.326186e+07  0.0  0.0
         rl      sdft cumulative_profit    4.426396e+07     4.417387e+07  0.0  0.0

==============================================================
  FORECASTING - MASE (lower is better)
==============================================================
           Task 1  Task 2
cl_method
ewc        2.9062  3.6191
naive      2.4678  2.2640
replay     2.1003  1.9556
sdft       1.5595  0.4903

==============================================================
  FORECASTING - sMAPE
==============================================================
             Task 1    Task 2
cl_method
ewc        104.4933  131.6897
naive       95.4880  111.2807
replay      91.0691  104.0968
sdft       100.1414  122.6640

==============================================================
  RL - CUMULATIVE PROFIT (higher is better)
==============================================================
                 Task 1        Task 2
cl_method
ewc        4.310701e+07  4.448476e+07
naive      4.329258e+07  4.511234e+07
recall     4.272142e+07  4.332225e+07
sdft       4.329156e+07  4.514628e+07

==============================================================
  RL - PRICING REGRET (lower is better)
==============================================================
            Task 1   Task 2
cl_method
ewc        31.8217  21.8476
naive      31.8056  21.8526
recall     31.8536  21.9645
sdft       31.8059  21.8422

==============================================================
  CL METRICS - BWT / FWT SUMMARY
==============================================================
 model_type cl_method    primary_metric  avg_final_perf  avg_online_perf  bwt  fwt
forecasting     naive              mase    2.049100e+00     2.682600e+00  0.0  0.0
forecasting       ewc              mase    3.256200e+00     3.269200e+00  0.0  0.0
forecasting    replay              mase    1.842500e+00     2.213400e+00  0.0  0.0
forecasting      sdft              mase    1.024600e+00     1.025200e+00  0.0  0.0
         rl     naive cumulative_profit    4.424801e+07     4.415691e+07  0.0  0.0
         rl       ewc cumulative_profit    4.374865e+07     4.384311e+07  0.0  0.0
         rl    recall cumulative_profit    4.278181e+07     4.326186e+07  0.0  0.0
         rl      sdft cumulative_profit    4.426396e+07     4.417387e+07  0.0  0.0

,model_type,cl_method,primary_metric,avg_final_perf,avg_online_perf,bwt,fwt
0,forecasting,naive,mase,2.049100e+00,2.682600e+00,0.0,0.0
1,forecasting,ewc,mase,3.256200e+00,3.269200e+00,0.0,0.0
2,forecasting,replay,mase,1.842500e+00,2.213400e+00,0.0,0.0
3,forecasting,sdft,mase,1.024600e+00,1.025200e+00,0.0,0.0
4,rl,naive,cumulative_profit,4.424801e+07,4.415691e+07,0.0,0.0
5,rl,ewc,cumulative_profit,4.374865e+07,4.384311e+07,0.0,0.0
6,rl,recall,cumulative_profit,4.278181e+07,4.326186e+07,0.0,0.0
7,rl,sdft,cumulative_profit,4.426396e+07,4.417387e+07,0.0,0.0